# Generated by Django 3.0.8 on 2020-07-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость недвижимости')),
                ('first_payment_amount', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='ПВ')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=2, verbose_name='Процент')),
                ('payment_period', models.IntegerField(verbose_name='Срок погашения в годах')),
                ('payment_start', models.DateField()),
            ],
            options={
                'db_table': 'credit',
            },
        ),
    ]
