# Generated by Django 3.2.20 on 2023-08-31 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mortgage',
            old_name='total_amount',
            new_name='credit_amount',
        ),
    ]
