# Generated by Django 3.2.20 on 2023-09-04 12:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0002_rename_total_amount_mortgage_credit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgage',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='first_payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(0)], verbose_name='first payment amount'),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='bank percent'),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='period',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='period'),
        ),
    ]
