# Generated by Django 3.2.4 on 2022-04-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgage',
            name='real_estate_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mortgage.realestateobject', unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='mortgage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mortgage.mortgage'),
        ),
    ]
