# Generated by Django 3.2.20 on 2023-09-06 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0003_auto_20230904_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgage',
            name='credit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(1)], verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='first_payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(1)], verbose_name='first payment amount'),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='period',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='period'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(1)], verbose_name='amount'),
        ),
    ]
