# Generated by Django 3.2.4 on 2022-04-16 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0004_auto_20220416_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgage',
            name='real_estate_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mortgage.realestateobject', unique=True, verbose_name='Объект недвижимости'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mortgage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mortgage.mortgage', verbose_name='Ипотечный кредит'),
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Цена'),
        ),
    ]
