# Generated by Django 3.2.4 on 2022-04-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0005_auto_20220416_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgage',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Процент'),
        ),
    ]
