# Generated by Django 3.2.4 on 2022-04-17 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0006_alter_mortgage_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank_percent',
        ),
    ]
