# Generated by Django 3.2.4 on 2022-04-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0007_remove_payment_bank_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='debt_decrease',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='debt_rest',
        ),
    ]
