# Generated by Django 3.2.4 on 2022-04-18 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mortgage', '0008_auto_20220418_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='mortgage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mortgages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='first_payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='first payment amount'),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='issue date'),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='percent'),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='period',
            field=models.IntegerField(verbose_name='period'),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='real_estate_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mortgage', to='mortgage.realestateobject', unique=True, verbose_name='real estate object'),
        ),
        migrations.AlterField(
            model_name='mortgage',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mortgage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='mortgage.mortgage', verbose_name='mortgage'),
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='address',
            field=models.CharField(max_length=200, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='area',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='area'),
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='built_year',
            field=models.IntegerField(verbose_name='build year'),
        ),
        migrations.AlterField(
            model_name='realestateobject',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, verbose_name='price'),
        ),
    ]
