# Generated by Django 3.2.4 on 2022-05-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0010_auto_20220512_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank_share',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True, verbose_name='bank share'),
        ),
        migrations.AddField(
            model_name='payment',
            name='debt_decrease',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True, verbose_name='debt decrease'),
        ),
        migrations.AddField(
            model_name='payment',
            name='debt_rest',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True, verbose_name='debt rest'),
        ),
    ]
