# Generated by Django 3.2.13 on 2022-06-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0011_auto_20220518_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_extra',
            field=models.BooleanField(default=False, verbose_name='is extra payment'),
        ),
    ]
