# Generated by Django 3.2.13 on 2022-09-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mortgage', '0012_payment_is_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank_share',
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True, verbose_name='bank amount'),
        ),
    ]
